#version: '3.8'
services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - app-network

  pm-database:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: laravel_project_management_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  npm:
    image: node:22.3
    container_name: npm
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: [ "sh", "-c", "npm install && npm run dev" ]
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"  # Expose Vite's default port
    networks:
      - app-network

  npm-build:
    image: node:22.3
    container_name: npm-build
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: [ "sh", "-c", "npm install && npm run build" ]
    environment:
      - NODE_ENV=development
    networks:
      - app-network

#  composer:
#    image: composer:latest
#    container_name: composer
#    working_dir: /var/www
#    volumes:
#      - .:/var/www
#    entrypoint: [ "composer" ]
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
