apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: laravel-pm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: quantiklab/laravel-pm-app:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_DATABASE
              value: "laravel_db"
            - name: DB_USERNAME
              value: "laravel_user"
            - name: DB_PASSWORD
              value: "securepassword"
          volumeMounts:
            - mountPath: /var/www/storage
              name: laravel-storage
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-pm-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: laravel
  namespace: laravel-pm
spec:
  selector:
    app: laravel

  ports:
    - protocol: "TCP"
      port: 9000
      targetPort: 9000
