# k8s/mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-database
spec:
  selector:
    matchLabels:
      app: pm-database
  replicas: 1
  template:
    metadata:
      labels:
        app: pm-database
    spec:
      containers:
        - name: pm-database
          image: pm-database-image:latest
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
