# k8s/mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pm-database-service
spec:
  selector:
    app: pm-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
