apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: laravel-pm
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server_tokens off;

        server {
            listen 80;
            server_name localhost;

            root /var/www/public;
            index index.php index.html index.htm;

            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }

            # Redirect all requests to React app (InertiaJS frontend)
            location /app {
                root /var/www/public;
                index index.html;
                try_files $uri /index.html;
            }

            # API requests should go to Laravel backend
            location /api/ {
                try_files $uri $uri/ /index.php?$query_string;
            }

            # PHP Processing (Laravel)
            location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass laravel:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }

            # Handle static assets (JS, CSS, images)
            location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|mp4|webm|ogg|mp3|wav|wasm)$ {
                expires 6M;
                access_log off;
                add_header Cache-Control "public";
            }

            error_page 404 /index.html;

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }
