apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pm-pv
  namespace: laravel-pm

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/laravel-pm-storage



---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pm-pvc
  namespace: laravel-pm

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

