# k8s/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: bGFyYXZlbF9wcm9qZWN0X21hbmFnZW1lbnQ=
  MYSQL_USER: cHJvamVjdG1hbmFnZW1lbnQ=
  MYSQL_PASSWORD: MTIzNA==
