# docker/mysql/Dockerfile
FROM mysql:8
#COPY my.cnf /etc/mysql/my.cnf

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=laravel_project_management
ENV MYSQL_USER=projectmanagement
ENV MYSQL_PASSWORD=1234

EXPOSE 3306
